param_rf = {'n_estimators': 450, 'min_samples_split': 11, 'min_samples_leaf': 13}
param_lr ={'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}
params_lgb = {
 "boosting_type": "gbdt",
 "objective": "binary",
 "metric": "auc",
 "learning_rate": 0.05,
 "n_estimators": 100,
 "n_jobs": 15,
 "seed": 27,
 'n_estimators': 2000,
 'reg_alpha': 2,
 'reg_lambda': 460,
 'max_depth': 4,
 'min_child_samples': 10,
 'num_leaves': 10,

}

param_cb = {
 "n_estimators": 800,
 "loss_function": "Logloss",
 "eval_metric": "AUC",
 "task_type": "CPU",
 "thread_count": -1,
 "early_stopping_rounds": 90,
 'custom_metric': ['AUC'],
 #     'cat_features' : categorical_features,
 "verbose": False,
 "random_seed": 42,
 "max_bin": 30,
 'learning_rate': 0.05,
 "max_depth": 2,
 "l2_leaf_reg": 28,
 #     'random_strength':150,
 #     'bagging_temperature':500,

}

params_xgb = {'booster': 'gbtree',
           'n_estimators': 135,
           "objective": "binary:logistic",
           'nthread': -1,
           'seed': 28,
           'learning_rate': 0.05,
            "eval_metric": "auc",
           'max_depth': 4,
           'reg_lambda': 3,
           'min_child_weight': 3,
           'gamma':0 }


target = 'Credit Default'
categorical_features = ['Home Ownership', 'Tax Liens', 'Purpose', 'Term']
discrete_feature = ['Years in current job', 'Number of Open Accounts',
                                 'Years of Credit History', 'Number of Credit Problems',
                                 'Months since last delinquent', 'Bankruptcies', 'Credit Score']
continuous_feature = ['Annual Income', 'Maximum Open Credit', 'Current Loan Amount',
                                   'Current Credit Balance', 'Monthly Debt']

count_columns = 17




good_list = ['Annual Income_**2',
 'Years in current job_**2',
 'Number of Open Accounts_**2',
 'Years of Credit History_**2',
 'Maximum Open Credit_**2',
 'Number of Credit Problems_**2',
 'Months since last delinquent_**2',
 'Bankruptcies_**2',
 'Current Loan Amount_**2',
 'Current Credit Balance_**2',
 'Monthly Debt_**2',
 'Credit Score_**2',
 'Credit Score_Credit Score_*',
 'Annual Income_**3',
 'Years in current job_**3',
 'Number of Open Accounts_**3',
 'Years of Credit History_**3',
 'Maximum Open Credit_**3',
 'Number of Credit Problems_**3',
 'Months since last delinquent_**3',
 'Bankruptcies_**3',
 'Current Loan Amount_**3',
 'Current Credit Balance_**3',
 'Monthly Debt_**3',
 'Credit Score_**3',
 'Annual Income_Credit Score_/',
 'Annual Income_Months since last delinquent_*',
 'Months since last delinquent_Annual Income_*',
 'Annual Income_Months since last delinquent_/',
 'Current Loan Amount_Credit Score_/',
 'Number of Open Accounts_Maximum Open Credit_*',
 'Maximum Open Credit_Number of Open Accounts_*',
 'Credit Score_Number of Open Accounts_/',
 'Number of Open Accounts_Current Credit Balance_*',
 'Current Credit Balance_Number of Open Accounts_*',
 'Months since last delinquent_Current Credit Balance_*',
 'Current Credit Balance_Months since last delinquent_*',
 'Bankruptcies_Years of Credit History_/',
 'Current Credit Balance_Months since last delinquent_/',
 'Annual Income_Credit Score_*',
 'Credit Score_Annual Income_*',
 'Number of Credit Problems_Credit Score_/',
 'Maximum Open Credit_log',
 'Current Loan Amount_Number of Credit Problems_/',
 'Years of Credit History_Current Credit Balance_/',
 'Annual Income_Number of Open Accounts_/',
 'Monthly Debt_Bankruptcies_/',
 'Maximum Open Credit_Years of Credit History_/',
 'Monthly Debt_Number of Credit Problems_/',
 'Current Credit Balance_Years of Credit History_/',
 'Years of Credit History_log',
 'Years of Credit History_Years of Credit History_*',
 'Months since last delinquent_Credit Score_/',
 'Number of Open Accounts_Number of Credit Problems_*',
 'Number of Credit Problems_Number of Open Accounts_*',
 'Number of Open Accounts_Years in current job_/',
 'Annual Income_Monthly Debt_*',
 'Monthly Debt_Annual Income_*',
 'Annual Income_Years of Credit History_*',
 'Years of Credit History_Annual Income_*',
 'Current Credit Balance_Maximum Open Credit_/',
 'Current Loan Amount_Current Loan Amount_*',
 'Months since last delinquent_Monthly Debt_*',
 'Monthly Debt_Months since last delinquent_*',
 'Maximum Open Credit_Number of Credit Problems_*',
 'Number of Credit Problems_Maximum Open Credit_*',
 'Monthly Debt_Months since last delinquent_/',
 'Number of Open Accounts_Monthly Debt_/',
 'Number of Credit Problems_Number of Open Accounts_/',
 'Maximum Open Credit_Bankruptcies_*',
 'Bankruptcies_Maximum Open Credit_*',
 'Credit Score_Monthly Debt_/',
 'Maximum Open Credit_Current Loan Amount_/',
 'Years of Credit History_Number of Credit Problems_/',
 'Monthly Debt_Credit Score_/',
 'Number of Credit Problems_Monthly Debt_*',
 'Monthly Debt_Number of Credit Problems_*',
 'Annual Income_Years in current job_*',
 'Years in current job_Annual Income_*',
 'Current Loan Amount_Number of Open Accounts_/',
 'Number of Open Accounts_Bankruptcies_*',
 'Bankruptcies_Number of Open Accounts_*',
 'Number of Credit Problems_Current Credit Balance_*',
 'Current Credit Balance_Number of Credit Problems_*',
 'Annual Income_Maximum Open Credit_*',
 'Maximum Open Credit_Annual Income_*',
 'Annual Income_log',
 'Credit Score_Maximum Open Credit_/',
 'Bankruptcies_Number of Open Accounts_/',
 'Months since last delinquent_Credit Score_*',
 'Credit Score_Months since last delinquent_*',
 'Maximum Open Credit_Months since last delinquent_*',
 'Months since last delinquent_Maximum Open Credit_*',
 'Months since last delinquent_Annual Income_/',
 'Maximum Open Credit_Maximum Open Credit_*',
 'Number of Open Accounts_Number of Credit Problems_/',
 'Number of Credit Problems_Current Credit Balance_/',
 'Current Credit Balance_Credit Score_/',
 'Number of Open Accounts_Current Loan Amount_/',
 'Credit Score_Months since last delinquent_/',
 'Current Loan Amount_Months since last delinquent_/',
 'Maximum Open Credit_Months since last delinquent_/',
 'Maximum Open Credit_Bankruptcies_/',
 'Maximum Open Credit_Credit Score_*',
 'Credit Score_Maximum Open Credit_*',
 'Maximum Open Credit_Current Loan Amount_*',
 'Current Loan Amount_Maximum Open Credit_*',
 'Number of Credit Problems_Credit Score_*',
 'Credit Score_Number of Credit Problems_*',
 'Years in current job_Monthly Debt_/',
 'Months since last delinquent_Months since last delinquent_*',
 'Years in current job_Number of Open Accounts_*',
 'Number of Open Accounts_Years in current job_*',
 'Number of Credit Problems_log',
 'Years in current job_Current Loan Amount_*',
 'Current Loan Amount_Years in current job_*',
 'Monthly Debt_Current Loan Amount_/',
 'Bankruptcies_Current Credit Balance_*',
 'Current Credit Balance_Bankruptcies_*',
 'Years in current job_Current Loan Amount_/',
 'Bankruptcies_Number of Credit Problems_/',
 'Bankruptcies_Bankruptcies_*',
 'Years in current job_Years in current job_*',
 'Years in current job_log',
 'Annual Income_Current Loan Amount_*',
 'Current Loan Amount_Annual Income_*',
 'Years in current job_Bankruptcies_*',
 'Bankruptcies_Years in current job_*',
 'Years in current job_Credit Score_*',
 'Credit Score_Years in current job_*',
 'Months since last delinquent_Current Loan Amount_*',
 'Current Loan Amount_Months since last delinquent_*',
 'Bankruptcies_log',
 'Bankruptcies_Current Loan Amount_*',
 'Current Loan Amount_Bankruptcies_*',
 'Months since last delinquent_Current Loan Amount_/',
 'Years of Credit History_Current Loan Amount_*',
 'Current Loan Amount_Years of Credit History_*',
 'Current Loan Amount_Monthly Debt_*',
 'Monthly Debt_Current Loan Amount_*',
 'Bankruptcies_Months since last delinquent_/',
 'Current Loan Amount_Current Credit Balance_*',
 'Current Credit Balance_Current Loan Amount_*',
 'Number of Credit Problems_Current Loan Amount_*',
 'Current Loan Amount_Number of Credit Problems_*',
 'Current Credit Balance_Credit Score_*',
 'Credit Score_Current Credit Balance_*',
 'Years of Credit History_Credit Score_*',
 'Credit Score_Years of Credit History_*',
 'Bankruptcies_Years in current job_/',
 'Monthly Debt_Credit Score_*',
 'Credit Score_Monthly Debt_*',
 'Number of Open Accounts_Current Loan Amount_*',
 'Current Loan Amount_Number of Open Accounts_*',
 'Months since last delinquent_log',
 'Months since last delinquent_Number of Open Accounts_/',
 'Bankruptcies_Current Loan Amount_/',
 'Number of Credit Problems_Bankruptcies_*',
 'Bankruptcies_Number of Credit Problems_*',
 'Months since last delinquent_Bankruptcies_*',
 'Bankruptcies_Months since last delinquent_*',
 'Years of Credit History_Current Loan Amount_/',
 'Current Loan Amount_log',
 'Number of Credit Problems_Current Loan Amount_/',
 'Annual Income_Current Loan Amount_/',
 'Bankruptcies_Monthly Debt_*',
 'Monthly Debt_Bankruptcies_*',
 'Number of Open Accounts_Credit Score_*',
 'Credit Score_Number of Open Accounts_*',
 'Current Loan Amount_Credit Score_*',
 'Credit Score_Current Loan Amount_*',
 'Bankruptcies_Credit Score_*',
 'Credit Score_Bankruptcies_*',
 'Years in current job_Current Credit Balance_/',
 'Bankruptcies_Current Credit Balance_/',
 'Bankruptcies_Credit Score_/',
 'Years of Credit History_Bankruptcies_*',
 'Bankruptcies_Years of Credit History_*',
 'Bankruptcies_Monthly Debt_/']




